This script retrievs data from the website https://www.slickcharts.com/sp500 through the HTML reading of the website. 

I was interested in the weights of the compamy weights composing the SP500 index on a daily basis

In [7]:
import os.path
import csv

import requests
from bs4 import BeautifulSoup 
import pandas as pd

In [8]:
url = 'https://www.slickcharts.com/sp500'

In [9]:
header = {
  "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36",
  "X-Requested-With": "XMLHttpRequest"
}

#we use this code to pretend to be a browser. Otherwise this errror appears: HTTP Error 403: Forbidden

r = requests.get(url, headers=header)

df = pd.read_html(r.text)[0]
df = df.drop(df.columns[0], axis=1)

In [11]:
df['Date'] = pd.Timestamp.today().strftime('%d-%m-%Y')
#df.set_index('Date') in case you want the date to be the index, change the setting of df in the next line accordingly
df[['Date','Company','Symbol', 'Weight', 'Price', 'Chg', '% Chg']] #rearrange te columns

,Date,Company,Symbol,Weight,Price,Chg,% Chg
0,04-05-2023,Apple Inc.,AAPL,7.278947,165.56,-2.98,(-1.77%)
1,04-05-2023,Microsoft Corporation,MSFT,6.601707,304.85,-0.57,(-0.18%)
2,04-05-2023,Amazon.com Inc.,AMZN,2.682812,103.78,0.15,(0.15%)
3,04-05-2023,NVIDIA Corporation,NVDA,2.015188,276.65,-5.45,(-1.93%)
4,04-05-2023,Alphabet Inc. Class A,GOOGL,1.821559,105.63,0.31,(0.29%)
...,...,...,...,...,...,...,...
498,04-05-2023,Zions Bancorporation N.A.,ZION,0.010419,20.64,-3.28,(-13.71%)
499,04-05-2023,Lincoln National Corp,LNC,0.009198,20.41,-0.14,(-0.69%)
500,04-05-2023,News Corporation Class B,NWS,0.006053,20.00,2.89,(16.88%)
501,04-05-2023,DISH Network Corporation Class A,DISH,0.005019,6.95,-0.10,(-1.35%)
502,04-05-2023,First Republic Bank,FRCB,0.000000,NaN,NaN,(NaN%)

The following piece of code attaches the new retrived data to an Excel file so the final result would be a csv file with all the
SP500 data weights day by day

In [6]:
#df = pd.DataFrame(df, columns=['Date','Company','Symbol', 'Weight', 'Price', 'Chg', '% Chg'])


print(df)
filename="S&P 500 Weights Components.csv"
header=True
if os.path.isfile(filename):
    header=False
df.to_csv(filename, mode="a", header=header, sep=",", quoting=csv.QUOTE_NONE, quotechar="",  escapechar="\\")

                       Company Symbol    Weight    Price    Chg     % Chg  \
0                   Apple Inc.   AAPL  6.596737   149.57  -0.07  (-0.05%)
1        Microsoft Corporation   MSFT  5.824742   272.67  -0.57  (-0.21%)
2              Amazon.com Inc.   AMZN  2.866565  2311.87   8.94   (0.39%)
3        Alphabet Inc. Class A  GOOGL  1.921463  2251.11   4.78   (0.21%)
4                    Tesla Inc   TSLA  1.808616   773.89  14.26   (1.88%)
..                         ...    ...       ...      ...    ...       ...
500  IPG Photonics Corporation   IPGP  0.010516   102.50   0.00   (0.00%)
501   News Corporation Class B    NWS  0.006251    17.81  -0.04  (-0.22%)
502  Under Armour Inc. Class A    UAA  0.005581    10.36   0.02   (0.19%)
503  Under Armour Inc. Class C     UA  0.005253     9.32  -0.06  (-0.64%)
504        Embecta Corporation   EMBC  0.000004    26.34   0.00   (0.00%)

           Date
0    31-05-2022
1    31-05-2022
2    31-05-2022
3    31-05-2022
4    31-05-2022
..          ...
500  31-05-2022
501  31-05-2022
502  31-05-2022
503  31-05-2022
504  31-05-2022

[505 rows x 7 columns]